{% set name = "cvxpy" %}
{% set version = "1.0.31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b398754f9e9ceaa46b07806b5ae85f90fd8de748475db22a6b99c5943cebe69d
  patches:
    - patches/0001-remove-pyproject.toml-requires-in-setup.py.patch

build:
  number: 1
  skip: true  # [py==27 and win]
  skip: true  # [py==27 and not x86_64]

# Need these up here for conda-smithy to handle them properly.
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
  run:
    - python

outputs:
  - name: cvxpy
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('cvxpy-base', exact=True) }}
        - osqp
        - ecos >=2
        - scs >=1.1.3
    test:
      imports:
        - cvxpy
        - cvxpy.cvxcore
        - cvxpy.cvxcore.python
      requires:
        - nose
      commands:
        - nosetests cvxpy
  - name: cvxpy-base
    build:
      script: {{ PYTHON }} -m pip install . --no-deps -vvv
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - python
        # very awkward matrix of "oldest on conda-forge >=1.15"
        - numpy 1.15  # [python_impl != "pypy" and py<38 and x86_64]
        - numpy 1.16  # [python_impl != "pypy" and py<38 and not x86_64]
        - numpy 1.17  # [python_impl != "pypy" and py>=38]
        - numpy 1.18  # [python_impl == "pypy"]
        - pip
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - scipy >=1.1.0
        - multiprocess
        - six
    test:
      imports:
        - cvxpy
        - cvxpy.cvxcore
        - cvxpy.cvxcore.python

about:
  home: http://www.cvxpy.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Python-embedded modeling language for convex optimization problems
  description: |
    CVXPY is a Python-embedded modeling language for convex optimization
    problems. It allows you to express your problem in a natural way that
    follows the math, rather than in the restrictive standard form required
    by solvers.
  doc_url: http://www.cvxpy.org/
  dev_url: https://github.com/cvxgrp/cvxpy

extra:
  recipe-maintainers:
    - SteveDiamond
    - akshayka
    - rileyjmurray
    - dougalsutherland
    - mcg1969
    - scopatz
    - h-vetinari
