{% set name = "cvxpy" %}
{% set version = "1.7.2" %}

package:
  name: cvxpy-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cvxpy-{{ version }}.tar.gz
  sha256: 89fbc51cca8136a9ef8232a5092a94205f69da5abf7fd05cb7ea7bf1205db7ea

build:
  number: 0
  skip: true  # [py<39]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
  run:
    - python

outputs:
  - name: cvxpy
    build:
      # Windows missing scs
      skip: true  # [win]
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('cvxpy-base', exact=True) }}
        - osqp >=0.6.2
        - clarabel >=0.5.0
        - scs >=3.2.4.post1
        - scipy >=1.13.0
        - {{ pin_compatible('numpy') }}
    test:
      requires:
        - pip
        - pytest
        # cvxopt required for tests, missing on s390x
        - cvxopt  # [not s390x]
      source_files:
        - cvxpy/tests
      imports:
        - cvxpy
        - cvxpy.cvxcore
        - cvxpy.cvxcore.python
      commands:
        {% set tests_to_skip = "_not_a_real_test" %}
        # test sets intentionally too small timelimit, and then fails
        {% set tests_to_skip = tests_to_skip + " or test_scipy_mi_time_limit_reached " %}
        - pytest cvxpy/tests -v -k "not ({{ tests_to_skip }})"  # [not s390x]
        - pip check

  - name: cvxpy-base
    build:
      script:
        - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - python
        - pip
        - numpy >=2.0.0
        - setuptools >=68.1.0
        - wheel
        - pybind11
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - scipy >=1.13.0
    test:
      # pip check fails for cvxpy-base due to checking for optional dependencies.
      imports:
        # public interface is defined (see #75) to be the content of
        # https://github.com/cvxpy/cvxpy/blob/master/cvxpy/__init__.py
        - cvxpy

about:
  home: https://www.cvxpy.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Python-embedded modeling language for convex optimization problems
  description: |
    CVXPY is a Python-embedded modeling language for convex optimization
    problems. It allows you to express your problem in a natural way that
    follows the math, rather than in the restrictive standard form required
    by solvers.
  doc_url: https://www.cvxpy.org
  dev_url: https://github.com/cvxpy/cvxpy

extra:
  recipe-maintainers:
    - timkpaine
    - SteveDiamond
    - akshayka
    - rileyjmurray
    - djsutherland
    - mcg1969
    - scopatz
    - h-vetinari
  feedstock-name: cvxpy
