{% set name = "cvxpy" %}
{% set version = "1.7.3" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 241d364f5962a1d68c4ae8393480766a09326e5771e2286d33a948e1976cbe70

build:
  number: 1
  skip: true  # [py<310]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
  run:
    - python

outputs:
  - name: cvxpy
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('cvxpy-base', exact=True) }}
        - osqp >=1.0.0
        - clarabel >=0.5
        - scs >=3.2.4.post1
        - numpy >=1.22.4
        - scipy >=1.13.0
      run_constrained:
        - cylp >=0.91.5
        - cuopt-cu12 >=25.5
        - ortools>=9.7,<9.15
        - xpress >=9.5
    test:
      source_files:
        - cvxpy/tests
      imports:
        - cvxpy
        - cvxpy.cvxcore
        - cvxpy.cvxcore.python
      requires:
        - pip
        - pytest
        - hypothesis
        - scipy
      commands:
        {% set tests_to_skip = "_not_a_real_test" %}
        # test sets intentionally too small timelimit, and then fails
        {% set tests_to_skip = tests_to_skip + " or test_scipy_mi_time_limit_reached " %}
        # Tests fail randomly on OSX on CI - cvxpy/tests/* Fatal Python error: Aborted
        - pip check
        - pytest cvxpy/tests -v -k "not ({{ tests_to_skip }})"  # [not osx]
  - name: cvxpy-base
    build:
      script:
        - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - pip
        - python
        - pybind11
        - setuptools >=68.1.0
        - numpy >=2.0.0
        - scipy >=1.13.0
      run:
        - python
        - numpy >=2.0.0
        - scipy >=1.13.0
    test:
      # pip check fails for cvxpy-base due to checking for optional dependencies.
      imports:
        # public interface is defined (see #75) to be the content of
        # https://github.com/cvxpy/cvxpy/blob/master/cvxpy/__init__.py
        - cvxpy

about:
  home: https://www.cvxpy.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Python-embedded modeling language for convex optimization problems
  description: |
    CVXPY is a Python-embedded modeling language for convex optimization
    problems. It allows you to express your problem in a natural way that
    follows the math, rather than in the restrictive standard form required
    by solvers.
  doc_url: https://www.cvxpy.org
  dev_url: https://github.com/cvxpy/cvxpy

extra:
  recipe-maintainers:
    - timkpaine
    - SteveDiamond
    - akshayka
    - rileyjmurray
    - djsutherland
    - mcg1969
    - scopatz
    - h-vetinari
  feedstock-name: cvxpy
