{% set name = "cvxpy" %}
{% set version = "1.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bd362f638c661cd532451948892647580d8726d5b70b557cdca3ebb993a23282

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  skip: true  # dependencies missing on:  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy 1.14
  run:
    - python
    - osqp
    - ecos >=2
    - scs >=1.1.3
    - multiprocess
    - fastcache
    - six
    - toolz
    - {{ pin_compatible('numpy') }}
    - scipy >=0.19

test:
  imports:
    - cvxpy
    - cvxpy.cvxcore
    - cvxpy.cvxcore.python
  requires:
    - nose
  commands:
    - nosetests cvxpy

about:
  home: http://www.cvxpy.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE  # in recipe for now, will be in next release
  summary: 'A Python-embedded modeling language for convex optimization problems'
  description: |
    CVXPY is a Python-embedded modeling language for convex optimization
    problems. It allows you to express your problem in a natural way that
    follows the math, rather than in the restrictive standard form required
    by solvers.
  doc_url: http://www.cvxpy.org/
  dev_url: https://github.com/cvxgrp/cvxpy

extra:
  recipe-maintainers:
    - dougalsutherland
