{% set name = "cvxpy" %}
{% set version = "1.1.7" %}

package:
  name: cvxpy-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 330eb76e8369c360b68d9231c6eb350848e373b5952134f9bfebaed1a4c4211f
  patches:
    - patches/0001-remove-pyproject.toml.patch
    - patches/0002-do-not-use-builtins-as-a-dict.patch
    - patches/0003-add-skip-for-test_ecos_bb_mi_lp_2.patch             # [aarch64]
    - patches/0004-reduce-decimal-precision-from-7-default-to-6.patch  # [aarch64]

build:
  number: 1

# Need these up here for conda-smithy to handle them properly.
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
  run:
    - python

outputs:
  - name: cvxpy
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('cvxpy-base', exact=True) }}
        - osqp
        - ecos >=2
        - scs >=1.1.3
    test:
      imports:
        - cvxpy
        - cvxpy.cvxcore
        - cvxpy.cvxcore.python
      requires:
        - nose
      commands:
        - nosetests cvxpy

  - name: cvxpy-base
    build:
      script: {{ PYTHON }} -m pip install . --no-deps -vvv
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - python
        # conda-forge recipe inserts oldest numpy per platform/runtime
        - numpy
        - pip
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - scipy >=1.1.0
    test:
      imports:
        - cvxpy
        - cvxpy.atoms
        - cvxpy.atoms.affine
        - cvxpy.atoms.elementwise
        - cvxpy.cvxcore
        - cvxpy.cvxcore.python
        - cvxpy.constraints
        - cvxpy.expressions
        - cvxpy.expressions.constants
        - cvxpy.interface
        - cvxpy.interface.numpy_interface
        - cvxpy.lin_ops
        - cvxpy.problems
        - cvxpy.reductions
        - cvxpy.reductions.complex2real
        - cvxpy.reductions.complex2real.atom_canonicalizers
        - cvxpy.reductions.dcp2cone
        - cvxpy.reductions.dcp2cone.atom_canonicalizers
        - cvxpy.reductions.eliminate_pwl
        - cvxpy.reductions.eliminate_pwl.atom_canonicalizers
        - cvxpy.reductions.qp2quad_form
        - cvxpy.reductions.qp2quad_form.atom_canonicalizers
        - cvxpy.reductions.eliminate_pwl.atom_canonicalizers
        - cvxpy.reductions.solvers
        - cvxpy.reductions.solvers.conic_solvers
        - cvxpy.reductions.solvers.qp_solvers
        - cvxpy.reductions.solvers.lp_solvers
        - cvxpy.tests
        - cvxpy.transforms
        - cvxpy.utilities
        - cvxpy.cvxcore.python

about:
  home: http://www.cvxpy.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Python-embedded modeling language for convex optimization problems
  description: |
    CVXPY is a Python-embedded modeling language for convex optimization
    problems. It allows you to express your problem in a natural way that
    follows the math, rather than in the restrictive standard form required
    by solvers.
  doc_url: http://www.cvxpy.org/
  dev_url: https://github.com/cvxgrp/cvxpy

extra:
  recipe-maintainers:
    - SteveDiamond
    - akshayka
    - rileyjmurray
    - djsutherland
    - mcg1969
    - scopatz
    - h-vetinari
  feedstock-name: cvxpy
