travis:
  secure:
    BINSTAR_TOKEN: pdgguljTrdKZlx12BIZGTTFZJi+YS0pze3zwM4rBn+gLnHcmEJf/PPjnuilbpI+cAhXcRpcAXr4jeEP5iBSDFH8eXRe91DsWBOsMBNRu2fLopLEekQ8Q2E+d9aoifQ85wCDWpLj9El+Lrw7VVTJm1ikkamZdGPLiB6hrA132bCSj8iSyXIPqYnPVm6y8olGpbi+TP/ZpNcasPRnhmseGJH+cHPksLtI42J8HHIzXGbmd5mh9eCCwGnvQk3Y4dRIVUYomagHH571fmTRmiVKCXj2VTP+Mv4jsYNTlYjBDAe4XqAhruKvttLjnvIZdT7Y7tJfgpl6WUxtfgqlgwKB/dLCsLDcnkOh7gVux960GGbbyQWBGrulQx3xLZ+WGZNYnp988IY+RKOE9XCLl10g4CX+OPP/2+68ToJ4mjsOD2VvNBunRCAhZOVD+tKLUTDIZrBBhNQZkv/daIFo9UdW/blF0NbLGhjmEOsCCRwBeUNJLmezF4XJhWoc68IJBmDKA4b9wWDtXNf0vXhNoZFPkdO7yj3V6FexqhAMTDQPWJABNBmMk29YGd8ohOmEpteNAWY3PNHMD9O0wzRGcYRhsu/bxfF1DGl0cZii9LjgGgenSqRlNCX7FvaxBGgctwwzjeRi1tduHqduIJkTTZLXnf6eey+SvQjAgBWKXUjfG/Kc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
